"""empty message

Revision ID: 3fc8947c2fa2
Revises: None
Create Date: 2016-10-18 15:35:03.119262

"""

# revision identifiers, used by Alembic.
revision = '3fc8947c2fa2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('users', sa.Column('email', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'name')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
